name: Release

on:
  schedule:
    - cron: '0 0 * * 1'   # Auto-release every Monday at midnight UTC
  workflow_dispatch:      # Manual trigger for quick fixes

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_TOKEN }}
